version: "3.9"
services:
  mysql:
    image: mysql:8.0.26
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=lab1
    ports:
      - "3305:3306"
  lab2:
    image: daneidmark/bank:0.0.1
    environment:
      - MYSQL_HOST=mysql
    ports:
      - "8082:8082"
    links:
      - mysql
  riskService:
    image: daneidmark/risk:0.0.1
    ports:
      - "8081:8080"